/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2012-09-23 15:39:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.bean.*;
import com.database.*;

public final class userinsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>   \r\n");
      out.write("\r\n");
      out.write("<title>增加用户</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function check(form){\r\n");
      out.write("\t\r\n");
      out.write("\t if(form.name.value==\"\"){\r\n");
      out.write("\t\t alert(\"用户姓名不能为空\");\r\n");
      out.write("\t\t return false;\r\n");
      out.write("\t }\r\n");
      out.write("\t if(form.password.value==\"\"){\r\n");
      out.write("\t\t alert(\"用户密码不能为空\");\r\n");
      out.write("\t\t return false;\r\n");
      out.write("\t }\r\n");
      out.write("\t if(form.rpassword.value!=form.password.value){\r\n");
      out.write("\t\t alert(\"两次的密码不一致\");\r\n");
      out.write("\t\t return false;\r\n");
      out.write("\t }\r\n");
      out.write("\t if(form.age.value==\"\"){\r\n");
      out.write("\t\t alert(\"用户年龄不能为空\");\r\n");
      out.write("\t\t return false;\r\n");
      out.write("\t }\r\n");
      out.write("\t if(form.telphone.value==\"\"){\r\n");
      out.write("\t\t alert(\"电话不能为空\");\r\n");
      out.write("\t\t return false;\r\n");
      out.write("\t }\r\n");
      out.write("\t if(form.address.value==\"\"){\r\n");
      out.write("\t\t alert(\"用户地址不能为空\");\r\n");
      out.write("\t\t return false;\r\n");
      out.write("\t }\r\n");
      out.write("\t return true;\r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

 request.setCharacterEncoding("gbk");
 if(request.getParameter("userinsert")!=null){
	
	 String name=request.getParameter("name");
	 
	 //判断userid和username是否重复
	 ArrayList<User> users =null;
	 users=new User_Operation().getUser();
	 
	 
	 String password=request.getParameter("password");
	 String sex=request.getParameter("sex");
	 int age=Integer.valueOf(request.getParameter("age"));
	 String telphone=request.getParameter("telphone");
	 String address=request.getParameter("address");
	 String power=request.getParameter("power");
	 
	 User user=new User();


	 user.setName(name);
	 user.setPassword(password);
	 user.setSex(sex);
	 user.setAge(age);
	 user.setTelphone(telphone);
	 user.setAddress(address);
	 user.setPower(power);
	 boolean consequence =new User_Operation().userinsert(user);
	 if(consequence){
		 out.println("<script type=\"text/javascript\">");
		 out.println("alert(\"数据插入成功\");");
		 out.println("open(\"usermanage.jsp\",\"_self\");");
		 out.println("</script>");
		 return;
	 }else{
		 out.println("<script type=\"text/javascript\">");
		 out.println("alert(\"数据插入失败\");");
		 out.println("open(\"usermanage.jsp\",\"_self\");");
		 out.println("</script>");
		 return; 
	 }
 }

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <form action=\"userinsert.jsp\" method=post onSubmit=\"return check(this);\">\r\n");
      out.write("  <input name=userinsert type=\"hidden\"/>\r\n");
      out.write("   <div style=\"border:10px solid #4169E1;width:95%;height:360px;\">\r\n");
      out.write("    <table style=margin-top:30px >\r\n");
      out.write("     <tr><td>用户名称：</td><td><input name=name type=\"text\" value=\"\" size=30/><font color=red>*</font></td></tr>\r\n");
      out.write("     <tr><td>用户密码：</td><td><input name=password type=\"text\" size=30/><font color=red>*</font></td></tr>\r\n");
      out.write("     <tr><td>确认密码：</td><td><input name=rpassword type=\"text\" size=30/><font color=red>*</font></td></tr>\r\n");
      out.write("     <tr><td>用户性别：</td><td><select name=sex><option value=男>男</option><option value=女>女</option></select></td></tr>\r\n");
      out.write("     <tr><td>用户年龄：</td><td><input name=age type=\"text\" size=30/><font color=red>*</font></td></tr>\r\n");
      out.write("     <tr><td>用户电话：</td><td><input name=telphone type=\"text\" size=30/><font color=red>*</font></td></tr>\r\n");
      out.write("     <tr><td>用户住址：</td><td><textarea name=address rows=3 cols=28></textarea><font color=red>*</font></td></tr>\r\n");
      out.write("     <tr><td>用户权限：</td><td><input name=power type=\"radio\" value=普通用户 checked/>普通用户<input name=power type=\"radio\" value=经理 />经理</td></tr>\r\n");
      out.write("    </table>\r\n");
      out.write("   </div> \r\n");
      out.write("   <input style=margin-left:100px;margin-top:20px; type=\"submit\" value=数据提交 /><a href=usermanage.jsp><input style=margin-left:50px; type=\"button\" value=返回 /></a>\r\n");
      out.write(" </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
