/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2012-09-29 05:19:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.bean.*;
import com.database.*;
import com.util.*;

public final class userpwdchange_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>   \r\n");
      out.write("<title>更改密码</title>\t\r\n");
      out.write("</head> \r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("  function check(){\r\n");
      out.write("     var opwd=document.getElementById(\"opwd\").value;\r\n");
      out.write("\t if(opwd==\"\"){\r\n");
      out.write("          alert(\"旧密码不能为空！\");\r\n");
      out.write("\t return false;   \r\n");
      out.write("\t }\r\n");
      out.write("     if(opwd!=document.getElementById(\"password\").value){\r\n");
      out.write("        alert(\"旧密码输入错误！\");\r\n");
      out.write("     return   false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\r\n");
      out.write("\t var pwd =document.getElementById(\"pwd\").value;\r\n");
      out.write("\t if(opwd==pwd){\r\n");
      out.write("      alert(\"新密码与旧密码一样，请重新输入新密码！\");\r\n");
      out.write("    return false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t if(pwd==\"\"){\r\n");
      out.write("\t alert(\"新密码不能为空！\");\r\n");
      out.write("\treturn  false;\r\n");
      out.write("\t }\r\n");
      out.write("\t if(pwd.length<1){\r\n");
      out.write("\t alert(\"密码不能少于1位\");\r\n");
      out.write("\t return  false;\t \r\n");
      out.write("\t }\r\n");
      out.write("\t  var rpwd=document.getElementById(\"rpwd\").value;\r\n");
      out.write("\t  if(rpwd!=pwd){\r\n");
      out.write("\t  alert(\"两次密码输入不一致!\");\r\n");
      out.write("\t return  false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t return true;\r\n");
      out.write("\t  \r\n");
      out.write("  }\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  ");

  request.setCharacterEncoding("gbk");
   long userid =Long.valueOf(request.getParameter("userid"));
   pageContext.setAttribute("userid",userid);
   String name =Tools.getstr(request.getParameter("name"));
   pageContext.setAttribute("name",name);
 
   
   if(request.getParameter("action")!=null){
	      String password=Tools.getstr(request.getParameter("passWord"));
		  User user=new User();
		  user.setUserid(userid);
		  user.setPassword(password);
		  boolean consequence=new User_Operation().changepwd(user);
		  if(session.getAttribute("username").equals(name)){
			 if(consequence){
				 out.println("<script>");
				 out.println("alert('密码更新成功,请重新登录');");
				 out.println("open('index.jsp','_parent');");
				 out.println("</script>"); 
			 }else{
				 out.println("<script>");
				 out.println("alert('密码更新失败');");
				 out.println("open('usermanage.jsp','_self');");
				 out.println("</script>");  
			 }
		}else{
			 if(consequence){
				 out.println("<script>");
				 out.println("alert('密码更新成功');");
				 out.println("open('usermanage.jsp','_self');");
				 out.println("</script>"); 
			 }else{
				 out.println("<script>");
				 out.println("alert('密码更新失败');");
				 out.println("open('usermanage.jsp','_self');");
				 out.println("</script>");  
			 }
		 }
	  }
    String password=Tools.getstr(request.getParameter("password"));
    pageContext.setAttribute("password",password);
  
      out.write("\r\n");
      out.write("  <body> \r\n");
      out.write("  <form action=\"userpwdchange.jsp\" method=get onSubmit=\"return check();\">\r\n");
      out.write("  <table>\r\n");
      out.write("  <tr><td><input type=\"hidden\" name=\"action\" value=\"\"></td>\r\n");
      out.write("  <td> <input type=\"hidden\" name=\"userid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("  <input name=\"password\" type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr><td>旧密码</td>\r\n");
      out.write("  <td><input id=\"opwd\" type=\"password\" name=\"oldPassWord\" ></td>\r\n");
      out.write("\r\n");
      out.write("  </tr>\r\n");
      out.write("   \r\n");
      out.write("  <tr><td>新密码</td>\r\n");
      out.write("  <td><input id=\"pwd\" type=\"password\" name=\"passWord\" ></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("\r\n");
      out.write("  <tr><td>确认密码</td>\r\n");
      out.write("  <td><input id=\"rpwd\" type=\"password\" name=\"NewPassWord\" ></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("    \r\n");
      out.write("  <tr>\r\n");
      out.write("  \r\n");
      out.write("  <td><input onclick=\"window.open('usermanage.jsp','_self')\" type=\"button\" value=\"返回\"></td>\r\n");
      out.write("  <td><input type=\"submit\" name=\"提交\" value=\"提交\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  </form>  \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
